// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwfEeFX0slGVaPJK1HTYBOQp4rUss2k_A',
    appId: '1:458207981918:web:d48732d2ec9e15719f1fcf',
    messagingSenderId: '458207981918',
    projectId: 'terabitit-dd771',
    authDomain: 'terabitit-dd771.firebaseapp.com',
    storageBucket: 'terabitit-dd771.appspot.com',
    measurementId: 'G-TC07CMSKS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA63er3dghxmlZFMAho1Oqj4hwtAv_129o',
    appId: '1:458207981918:android:39c4614903179fe89f1fcf',
    messagingSenderId: '458207981918',
    projectId: 'terabitit-dd771',
    storageBucket: 'terabitit-dd771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHmYBDPk3pP2dvvfuvfJiglqEXdwLmfEo',
    appId: '1:458207981918:ios:640fb435934e06a49f1fcf',
    messagingSenderId: '458207981918',
    projectId: 'terabitit-dd771',
    storageBucket: 'terabitit-dd771.appspot.com',
    iosBundleId: 'com.example.terabitIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHmYBDPk3pP2dvvfuvfJiglqEXdwLmfEo',
    appId: '1:458207981918:ios:640fb435934e06a49f1fcf',
    messagingSenderId: '458207981918',
    projectId: 'terabitit-dd771',
    storageBucket: 'terabitit-dd771.appspot.com',
    iosBundleId: 'com.example.terabitIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwfEeFX0slGVaPJK1HTYBOQp4rUss2k_A',
    appId: '1:458207981918:web:f923d0799b9b68f29f1fcf',
    messagingSenderId: '458207981918',
    projectId: 'terabitit-dd771',
    authDomain: 'terabitit-dd771.firebaseapp.com',
    storageBucket: 'terabitit-dd771.appspot.com',
    measurementId: 'G-4CT3JYQ4VT',
  );
}
